### ISSUE TITLE
Ability to configure NTP servers via cloud-config

### ISSUE THREAD

**Issue by zjs** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#101]
/kind feature

**Describe the solution you'd like**
I would like to be able to define NTP servers as a part of cloud-config.

I may have NTP servers internal to my datacenter which I want my nodes to use.

**Anything else you would like to add:**
A golang template for configuring this could look something like:

```
{{- if .NTPServers }}
ntp:
  enabled: true
  servers:
  {{- range .NTPServers }}
  - {{ . }}
  {{- end }}
{{- end }}
```

**Comment by detiber** [comment]
It doesn't look like ntp is supported in ignition, so this may present issues when we look at adding support for additional types of output.

**Comment by dennisme** [comment]
For CoreOS we run timesyncd. Would look something like this:

```yaml
systemd:
  storage:
    directories:
    files:
      - path: /etc/systemd/timesyncd.conf
        filesystem: root
        mode: 0644
        contents:
          inline: |
            [Time]
            NTP=server1.com sever2.com 
```
