### ISSUE TITLE
Consider using konfigadm instead of cloud-init

### ISSUE THREAD

**Issue by moshloop** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#111]
/kind feature

[konfigadm](https://github.com/moshloop/konfigadm) is a declarative, intent-based library/CLI for configuring hosts in a kubernetes environment.   

This would help solve #108 #102  #101 #100 #41 

konfigadm *compiles* down to bash or cloud-init - adding an ignition config or ignition + bash output is fairly trivial to implement and test.

Konfigadm also includes full golang structs for cloud-init, so that user-supplied configuration can be validated and supporting fail-fast behaviour. 

konfigadm is explicit about the OS versions supported, and tests this support using E2E matrix tests (currently via docker+bash output, but I plan on adding cloud-init as soon as I find/build a nested virtualization CI environment)

#11 #12 #13  could then effectively be closed by deferring to konfigadm's support matrix and E2E tests

In addition, konfigadm can install and configure all kubernetes dependencies, making prebuilt images optional, and is one of the options available as part of image-builder sub-project. 
```yaml
kubernetes:
  version: 1.15.1
container_runtime:
  type: docker
```

From an implementation perspective, the spec could be updated as follows:
```yaml
spec:
    kubeadm:
      ...
    konfigadm:
      ...
```
