### ISSUE TITLE
can't add node-role label with JoinConfiguration

### ISSUE THREAD

**Issue by de13** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#284]
/kind bug

/kind bug

**What steps did you take and what happened:**

```yaml
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: ""
    token: ""
    unsafeSkipCAVerification: true
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "gce"
    node-labels: node-role.kubernetes.io/worker=
```

Kubelet in unhealthy state when using this JoinConfiguration. I have the following error:

```
Nov  2 06:56:02 dday-instance-2 kubelet[6823]: F1102 06:56:02.583158    6823 server.go:185] unknown 'kubernetes.io' or 'k8s.io' labels specified with --node-labels: [node-role.kubernetes.io/worker]
Nov  2 06:56:02 dday-instance-2 kubelet[6823]: --node-labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, failure-domain.kubernetes.io/region, failure-domain.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/instance-type, kubernetes.io/os)
```

However, manually putting this label on the node works.

**What did you expect to happen:**

Node labeled with `node-role.kubernetes.io/worker=`

**Anything else you would like to add:**

Othe kind of labels works fine `foo=bar` `node.kubernetes.io/worker=` but node-role doesn't work.

**Environment:**

- Kubernetes version: (use `kubectl version`):  v1.16.2
- OS (e.g. from `/etc/os-release`):  Debian 9.11

**Environment:**

- Cluster API version: v1.16.2
- Cluster API Bootstrap Provider Kubeadm version: 1.16.2
- Cluster API Infrastructure Provider version:
- Kubernetes version: (use `kubectl version`): 1.16.2
- OS (e.g. from `/etc/os-release`): Debian 9.11
