### ISSUE TITLE
k8s-ci-robot no longer has proper permissions on this repo

### ISSUE THREAD

**Issue by cjwagner** [kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#286]
/kind bug

```yaml
{
  component: "hook"   
  error: "status code 422 not one of [200], body: {"message":"Validation Failed","errors":[{"resource":"Label","code":"unprocessable","field":"data","message":"k8s-ci-robot does not have permission to add labels in this repository."}],"documentation_url":"https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue"}"   
  event-GUID: "a116f700-20f3-11ea-914b-b1c11c8c4e13"   
  event-type: "pull_request_review"   
  file: "prow/hook/events.go:389"   
  func: "k8s.io/test-infra/prow/hook.(*Server).handleGenericComment.func1"   
  level: "error"   
  msg: "Error handling GenericCommentEvent."   
  org: "kubernetes-sigs"   
  plugin: "lgtm"   
  pr: 285   
  repo: "cluster-api-bootstrap-provider-kubeadm"   
  review: 333455499   
  reviewer: "vincepri"   
  url: "https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/285#pullrequestreview-333455499"   
}
```

"k8s-ci-robot does not have permission to add labels in this repository."

k8s-ci-robot should have permissions at the org level, but maybe they were manually revoked at the repo level? I'm not exactly sure how this could happen. @cblecker @stevekuznetsov do you know what might have happened or how we can prevent this?
cc @justinsb @detiber as repo OWNERS
